<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="camelProperties" nsURI="http://www.talend.org/CamelProperties"
    nsPrefix="CamelProperties">
  <eClassifiers xsi:type="ecore:EClass" name="BeanItem" eSuperTypes="../../org.talend.model/model/properties.ecore#//RoutineItem"/>
  <eClassifiers xsi:type="ecore:EClass" name="CamelProcessItem" eSuperTypes="../../org.talend.model/model/properties.ecore#//ProcessItem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="springContent" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exportMicroService" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RouteResourceItem" eSuperTypes="../../org.talend.model/model/properties.ecore#//FileItem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bindingExtension" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RouteDocumentItem" eSuperTypes="../../org.talend.model/model/properties.ecore#//DocumentationItem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bindingExtension" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RouteletProcessItem" eSuperTypes="../../org.talend.model/model/properties.ecore#//ProcessItem"/>
</ecore:EPackage>
