<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="services" nsURI="http://www.talend.org/Services" nsPrefix="Services">
  <eClassifiers xsi:type="ecore:EClass" name="ServiceItem" eSuperTypes="../../org.talend.model/model/properties.ecore#//ConnectionItem"/>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceOperation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referenceJobId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="documentation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inBinding" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceConnection" eSuperTypes="../../org.talend.model/model/metadata.ecore#//Connection">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="WSDLPath" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="servicePort" upperBound="-1"
        eType="#//ServicePort"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="additionalInfo" upperBound="-1"
        eType="ecore:EClass ../../org.talend.model/model/properties.ecore#//AdditionalInfoMap"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServicePort">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceOperation" upperBound="-1"
        eType="#//ServiceOperation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="additionalInfo" upperBound="-1"
        eType="ecore:EClass ../../org.talend.model/model/properties.ecore#//AdditionalInfoMap"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
